server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atm?characterEncoding=UTF-8&serverTimezone=UTC
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
